<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LuxDrive.Data.Models\LuxDrive.Data.Models.csproj" />
    <ProjectReference Include="..\LuxDrive.Data\LuxDrive.Data.csproj" />
    <ProjectReference Include="..\LuxDrive.Services\LuxDrive.Services.csproj" />
    <ProjectReference Include="..\LuxDrive.ViewModels\LuxDrive.ViewModels.csproj" />
  </ItemGroup>

</Project>
